@Title 1 : Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.

In [4]:
import numpy as np
import logging

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s',
handlers=[
        logging.StreamHandler(),  # Stream logs to the console
        logging.FileHandler('numpy.log')  # Store logs in a file
    ])
    # Create a logger
logger = logging.getLogger('my_logger')

In [8]:
my_arr=list(map(int,input("Enter a values in list").split()))
numpy_arr=np.array(my_arr)
print(numpy_arr)

@Title 2 : Write a Python program to create a 3x3 matrix with values ranging from 2 to 10.


In [ ]:
my_arr=np.arange(2,8).reshape(2,3)
print(f"The 2d array is :\n {my_arr}")

@Title 3 :Write a Python program to create a null vector of size 10 and update sixth value to 11

In [ ]:
my_arr=np.zeros(10)
np.insert(my_arr,6,11)

@Title 4 : Write a Python program to reverse an array (first element becomes last).

In [63]:
my_arr=list(map(int,input("Enter a values in list").split()))
my_arr=np.array(my_arr)
new_array=np.flip(my_arr)

@Title 5 : Write a Python program to create a 2d array with 1 on the border and 0 inside.

In [ ]:
my_arr=np.full((8,8),(0))
my_arr[1:-1,1:-1]=0
print(my_arr)

@Title 6: Write a Python program to create a 2d array with 0 on the border and 1 inside.

In [81]:
my_arr=np.ones((3,3),dtype=int)
new = np.pad(my_arr, pad_width=1, mode='constant', constant_values=0)
print(new)

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


@Title 7: Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.


In [83]:
my_arr=np.ones((8,8),int)
my_arr[0:9:2,1:8:2]=0
my_arr[1:8:2,0:9:2]=0
print(my_arr)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


@Title 8:Write a Python program to convert a list and tuple into arrays.

In [91]:
lst=[1,2,3,4,5,6]
tupple=[(0,10),(20,30),(40,50)]
tuple_arr=np.array(tupple)
lst_arr=np.array(lst)
print(lst_arr)
print(tuple_arr)

[1 2 3 4 5 6]
[[ 0 10]
 [20 30]
 [40 50]]


@Title 9: Write a Python program to append values to the end of an array.

In [45]:
og_list=[10, 20, 30]
og_list=np.append(og_list,[40,50,60])
print(og_list)

[10 20 30 40 50 60]


@Title 10: Write a Python program to find the real and imaginary parts of an array of complex
numbers

In [53]:
equation= np.complex_(1.00000000+0.70710678j)
print(f"the real part is {equation.real}\n the imaginary part is {equation.imag}")

the real part is 1.0
 the imaginary part is 0.70710678


@Title 11: Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.


In [3]:
new_list=[1,2,3,4,5]
new_list=np.array(new_list)
print(f"The size of array is: {new_list.size}")
print(f"The size of array in bytes: {new_list.itemsize}")
print(f"Total bytes consumed by the elements of the array: {new_list.nbytes}")


The size of array is: 5
The size of array in bytes: 4
Total bytes consumed by the elements of the array: 20


@Title 12: Write a Python program to find common values between two arrays


In [93]:
try:
    my_list1=np.array(list(map(int,input("Enter a values in list 1").split())))
    my_list2=np.array(list(map(int,input("Enter a values in list 2").split())))
    print(f"The common elements between two arrays are {np.intersect1d(my_list1,my_list2)}")  
    logger.info("Program executed Successfully!!")
except Exception as e:
    logger.error(e)


2023-06-26 11:44:03,989 - INFO - Program executed Successfully!!


The common elements between two arrays are [1]


@Title 13: Write a Python program to find set diifrence between two arrays

In [8]:
try:
    my_list1=np.array(list(map(int,input("Enter a values in list 1").split())))
    my_list2=np.array(list(map(int,input("Enter a values in list 2").split())))
    print(f"The set diffrence between two arrays are {np.setdiff1d(my_list1,my_list2)}")  
    logger.info("Program executed Successfully!!")
    
except Exception as e:
    logger.error(e)


2023-06-25 12:42:41,443 - INFO - Program executed Successfully!!


The set diffrence between two arrays are [2 3]


@Title 14: Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays

In [9]:
try:
    my_list1=np.array(list(map(int,input("Enter a values in list 1").split())))
    my_list2=np.array(list(map(int,input("Enter a values in list 2").split())))
    print(f"The set exclusive between two arrays are {np.setxor1d(my_list1,my_list2)}")  
    logger.info("Program executed Successfully!!")

except Exception as e:
    logger.error(e)


2023-06-25 12:46:03,785 - INFO - Program executed Successfully!!


The set exclusive between two arrays are [4 5]


@Title 15: Write a Python program compare two arrays using numpy

In [10]:
try:
    my_list1=np.array(list(map(int,input("Enter a values in list 1").split())))
    my_list2=np.array(list(map(int,input("Enter a values in list 2").split())))
    print(f" greater than : {np.greater(my_list1,my_list2)}")
    print(f" greater than equal to : {np.greater_equal(my_list1,my_list2)}")
    print(f" less than : {np.less(my_list1,my_list2)}")
    print(f" less than equal to : {np.less_equal(my_list1,my_list2)}")

    logger.info("Program executed Successfully!!")
except Exception as e:
    logger.error(e)


2023-06-25 12:50:39,155 - INFO - Program executed Successfully!!


 greater than : [ True  True]
 greater than equal to : [ True  True]
 less than : [False False]
 less than equal to : [False False]


@Title 16:Write a Python program to save a NumPy array to a text file.


In [94]:
try:
    my_list1=np.array(list(map(int,input("Enter a values in list 1").split())))
    np.savetxt("my_list1.txt",my_list1,fmt="%d") 
    logger.info("Program executed Successfully!!")
except Exception as e:
    logger.error(e)


2023-06-26 11:46:06,755 - INFO - Program executed Successfully!!


@Title 17:Write a Python program to create a contiguous flattened array

In [20]:
try:
    list1_num=int(input("Enter a number of list"))
    og_array=[]
    for i in range(list1_num):
        my_list=np.array(list(map(int,input(f"Enter a values in list {i}").split())))
        og_array.append(my_list2)
    print(f"The contiguous flattened array {np.ravel(og_array)}")  
    logger.info("Program executed Successfully!!")
except Exception as e:
    logger.error(e)

Enter array of 2


2023-06-25 18:50:58,596 - INFO - Program executed Successfully!!


Enter array of 3
The contiguous flattened array [1 5 3]


@Title 18:Write a Python program to create a 3-D array with ones on a diagonal and zeros


In [22]:
try:
    size=int(input("Enter a size of 3d array"))
    new_array=np.eye(size)
    print(new_array)  
    logger.info("Program executed Successfully!!")  
except Exception as e:
    logger.error(e)


2023-06-25 18:58:48,193 - INFO - Program executed Successfully!!


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


@Title 19:Write a Python program to change the data type of an array.


In [58]:
my_num=np.array(list(map(int,input(f"Enter a values in list").split())))
print(f"The data type of list is: {my_num.dtype}")
my_float=my_num.astype(float)
print(f"The data type of list is: {my_float.dtype}")

The data type of list is: int32
The data type of list is: float64


@Title 20: Write a Python program to create an array which looks like below array.

In [78]:
try:
    size=int(input("Enter a size of 3d array"))
    new_array=np.tril([[1,1,1],[1,1,1],[1,1,1],[1,1,1]],-1)
    print(new_array)    
    logger.info("Program executed Successfully!!")
except Exception as e:
    logger.error(e)


2023-06-26 11:28:32,944 - INFO - Program executed Successfully!!


[[0 0 0]
 [1 0 0]
 [1 1 0]
 [1 1 1]]


@Title 21: Write a Python program to create an array which looks like below array.

In [90]:
try:
    my_list1=np.array([[0, 1, 3], [5, 7, 9]])
    my_list2=np.array([[0, 2, 4], [6, 8, 10]])
    print(f"The two list are {np.concatenate((my_list1,my_list2),1)}")  

    logger.info("Program executed Successfully!!")
except Exception as e:
    logger.error(e)



2023-06-26 11:34:57,102 - INFO - Program executed Successfully!!


The two list are [[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


@Title 22: Write a Python program to make an array immutable (read-only).

In [49]:
try:
    my_list1=np.array([0, 1, 3,5, 7, 9])
    my_list1.flags.writeable=False
    my_list1[0]=5
    logger.info("Program executed Successfully!!")
except Exception as e:
    logger.error(e)

2023-06-25 20:32:45,249 - ERROR - assignment destination is read-only


@Title 23: Write a Python program to create an array of (3, 4) shape, multiply every element

In [48]:
try:
    my_list=np.array(np.arange(1,13).reshape(3,4))
    my_list=my_list*3
    print(my_list)
    logger.info("Program executed Successfully!!")
except Exception as e:
    logger.error(e)

2023-06-25 20:32:15,148 - INFO - Program executed Successfully!!


[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]]


@Title 24: Write a Python program to convert a NumPy array into Python list structure.

In [50]:
try:
    my_array=np.array([0, 1, 3,5, 7, 9])
    new_list=my_array.tolist()
    print(new_list)
    logger.info("Program executed Successfully!!")
except Exception as e:
    logger.error(e)

2023-06-25 20:37:54,309 - INFO - Program executed Successfully!!


[0, 1, 3, 5, 7, 9]


@Title 25: Write a Python program to convert a NumPy array into Python list structure.
            Print array values with precision 3

In [52]:
try:
    my_array=np.array([ 0.26153123, 0.52760141 ,0.5718299, 0.5927067, 0.7831874, 0.69746349,0.35399976 ,0.99469633, 0.0694458 ,0.54711478])
    precesion=3
    my_array=np.around(my_array,decimals=precesion)
    new_list=my_array.tolist()
    print(new_list)
    logger.info("Program executed Successfully!!")
except Exception as e:
    logger.error(e)

2023-06-25 20:42:14,470 - INFO - Program executed Successfully!!


[0.262, 0.528, 0.572, 0.593, 0.783, 0.697, 0.354, 0.995, 0.069, 0.547]


@Title 26: Write a Python program to suppresses the use of scientific notation for small
numbers in numpy array

In [53]:
try:
    my_array = np.array([1.60000000e-10, 1.60000000e+00, 1.20000000e+03, 2.35000000e-01])
    np.set_printoptions(formatter={'float': '{:0.3f}'.format})
    print(my_array)
    logger.info("Program executed Successfully!!")
except Exception as e:
    logger.error(e)

2023-06-25 20:45:17,225 - INFO - Program executed Successfully!!


[0.000 1.600 1200.000 0.235]


@Title 27: Write a Python program to how to add an extra column to an numpy array

In [112]:
x = np.array([[10,20,30], [40,50,60]])
y = np.array([[100], [200]])
print(np.append(x, y, axis=1))

[[ 10  20  30 100]
 [ 40  50  60 200]]


@Title 28:  Write a Python program to remove specific elements in a numpy arr

In [95]:

my_array=np.array([0, 1, 3, 5, 7, 9])
try:
    element_index=list(map(int,input("Enter a index ").split()))
    for i in element_index:
        if i<len(my_array):
            my_array = np.delete(my_array,i)
        else:
            print(f"Index {i} is out of bond")
    print(my_array)
    logger.info("Program executed Successfully!!")
except Exception as e:
        logger.error(e)


2023-06-26 11:52:25,202 - INFO - Program executed Successfully!!


[0 3 5 7 9]
